import { MigrationInterface, QueryRunner } from "typeorm";

export class INITMODELS1714403840321 implements MigrationInterface {
    name = 'INITMODELS1714403840321'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "characterAlternatives" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying, "characterNameId" uuid, CONSTRAINT "PK_da1b4aad44d674f8b076911b582" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "characterAlternativeSpoilers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying, "characterNameId" uuid, CONSTRAINT "PK_da70d1915f479a3fe01e0c4c55b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "characterNames" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "first" character varying, "middle" character varying, "last" character varying, "full" character varying, "native" character varying, CONSTRAINT "PK_ef1b2a4d877e4f62b339e8d4121" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "characterImages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "large" character varying, "medium" character varying, CONSTRAINT "PK_b104a1bdbcf91476a0e232b06e6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "airingScheduleEdges" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "idAnilist" integer NOT NULL, "nodeId" uuid, "airingScheduleConnectionId" uuid, CONSTRAINT "REL_428b3a1db4a2d7f540e74d287a" UNIQUE ("nodeId"), CONSTRAINT "PK_c55d7007b009e05cde78eefe8e7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e64f63b15a5c37eae8138adce9" ON "airingScheduleEdges" ("idAnilist") `);
        await queryRunner.query(`CREATE TABLE "airingScheduleConnections" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_25220d6422a8f24e3705da691b2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "airingSchedules" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "idAnilist" integer NOT NULL, "airingAt" integer NOT NULL, "timeUntilAiring" integer NOT NULL, "episode" integer NOT NULL, "mediaId" integer NOT NULL, "animeId" uuid, "airingScheduleConnectionId" uuid, CONSTRAINT "REL_1ec3ba088e8c9ab23538239704" UNIQUE ("animeId"), CONSTRAINT "PK_7a3e4e91787f4f0bd29809923dc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_f6fc472834012ed0d5bf7bf52e" ON "airingSchedules" ("idAnilist") `);
        await queryRunner.query(`CREATE TABLE "animeTitles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "romaji" character varying, "english" character varying, "vietnamese" character varying, "native" character varying, "userPreferred" character varying, CONSTRAINT "PK_9e5443bb94c7e923d71b4db116b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "animeDescriptions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "english" character varying, "englishAIGenerate" character varying, "vietnamese" character varying, "vietnameseAIGenerate" character varying, CONSTRAINT "PK_e66871fabb93aafc0f8ee981f37" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "animeTrailers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "_id" character varying, "site" character varying, "thumbnail" character varying, CONSTRAINT "PK_a77bf63d549607c5af6b2ce0026" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "animeCoverImages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "extraLarge" character varying, "large" character varying, "medium" character varying, "color" character varying, CONSTRAINT "PK_d48f75677b94cfaeafe33ee6d13" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "animeGenres" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "genre" character varying NOT NULL, "description" character varying, CONSTRAINT "PK_db3cbdfeb31250962e0ac8968b6" PRIMARY KEY ("id", "genre"))`);
        await queryRunner.query(`CREATE TABLE "animeSynonyms" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "synonym" character varying, "animeId" uuid, CONSTRAINT "PK_f2b0acc6ceb1b5a2250c50bfd40" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "animeTags" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "idAnilist" integer NOT NULL, "name" character varying NOT NULL, "descriptionEn" character varying, "descriptionVi" character varying, "category" character varying, "rank" integer, "isGeneralSpoiler" boolean, "isMediaSpoiler" boolean, "isAdult" boolean, CONSTRAINT "PK_2983b8ac3bc818cdc5e3b7729ac" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_8c8af58bbb2debc62de8157bc9" ON "animeTags" ("idAnilist") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_c983c0d7a7d44ce4a57858e2bd" ON "animeTags" ("name") `);
        await queryRunner.query(`CREATE TYPE "public"."animeRanks_type_enum" AS ENUM('RATED', 'POPULAR')`);
        await queryRunner.query(`CREATE TYPE "public"."animeRanks_format_enum" AS ENUM('TV', 'TV_SHORT', 'MOVIE', 'SPECIAL', 'OVA', 'ONA', 'MUSIC')`);
        await queryRunner.query(`CREATE TYPE "public"."animeRanks_season_enum" AS ENUM('WINTER', 'SPRING', 'SUMMER', 'FALL')`);
        await queryRunner.query(`CREATE TABLE "animeRanks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "idAnilist" integer NOT NULL, "rank" integer NOT NULL, "type" "public"."animeRanks_type_enum" NOT NULL, "format" "public"."animeRanks_format_enum" NOT NULL, "year" integer, "season" "public"."animeRanks_season_enum" NOT NULL, "allTime" boolean, "context" character varying NOT NULL, "animeId" uuid, CONSTRAINT "PK_19490045981b0385a2ef6c0b0e8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_bd2b05ba1470f6df4dcf05b5d2" ON "animeRanks" ("idAnilist") `);
        await queryRunner.query(`CREATE TABLE "fuzzyDates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "year" integer, "month" integer, "day" integer, CONSTRAINT "PK_a0eaf53705a739b10db0af5a25f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "characters" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "idAnilist" integer NOT NULL, "description" character varying, "gender" character varying, "age" character varying, "bloodType" character varying, "nameId" uuid, "characterConnectionId" uuid, "imageId" uuid, "dateOfBirthId" uuid, CONSTRAINT "REL_f43955db99a8d593b618e2d392" UNIQUE ("nameId"), CONSTRAINT "REL_6d88ae463bc7e775b6679f7adb" UNIQUE ("imageId"), CONSTRAINT "REL_158bcaae805ac42d87eaf9f7cf" UNIQUE ("dateOfBirthId"), CONSTRAINT "PK_9d731e05758f26b9315dac5e378" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_8b2fe437e585f2a356df6e863b" ON "characters" ("idAnilist") `);
        await queryRunner.query(`CREATE TABLE "staffRoleTypes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "roleNotes" character varying, "dubGroup" character varying, "animeEdgeId" uuid, "voiceActorId" uuid, CONSTRAINT "REL_f9c4eac13608dd9f2eef4265dd" UNIQUE ("voiceActorId"), CONSTRAINT "PK_dc03054070cc10610716078e5af" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."animeEdges_relationtype_enum" AS ENUM('ADAPTATION', 'PREQUEL', 'SEQUEL', 'PARENT', 'SIDE_STORY', 'CHARACTER', 'SUMMARY', 'ALTERNATIVE', 'SPIN_OFF', 'OTHER', 'SOURCE', 'COMPILATION', 'CONTAINS')`);
        await queryRunner.query(`CREATE TYPE "public"."animeEdges_characterrole_enum" AS ENUM('MAIN', 'SUPPORTING', 'BACKGROUND')`);
        await queryRunner.query(`CREATE TABLE "animeEdges" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "idAnilist" integer NOT NULL, "relationType" "public"."animeEdges_relationtype_enum", "isMainStudio" boolean NOT NULL, "characterRole" "public"."animeEdges_characterrole_enum", "characterName" character varying, "roleNotes" character varying, "dubGroup" character varying, "staffRole" character varying, "favouriteOrder" integer, "animeConnectionId" uuid, "nodeId" uuid, CONSTRAINT "REL_63e3b515675c9db42a3533a9a1" UNIQUE ("nodeId"), CONSTRAINT "PK_82b726a20f2f4253aed121c38d0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_ad4ef85b2cacf6c42f6a5769c8" ON "animeEdges" ("idAnilist") `);
        await queryRunner.query(`CREATE TABLE "animeConnections" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_f4a9b992c8cfdb7df56fcdab690" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "animeTrends" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "mediaId" integer NOT NULL, "date" integer NOT NULL, "trending" integer NOT NULL, "averageScore" integer, "popularity" integer, "inProgress" integer, "releasing" boolean NOT NULL, "episode" integer, "animeId" uuid, "animeTrendConnectionId" uuid, CONSTRAINT "REL_d4e375a27a2792b08744f7ba66" UNIQUE ("animeId"), CONSTRAINT "PK_e76cf73b9652d1698572e11f2ca" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "animeTrendEdges" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "nodeId" uuid, "animeTrendConnectionId" uuid, CONSTRAINT "REL_be6efd17993fc49a33cbca09c4" UNIQUE ("nodeId"), CONSTRAINT "PK_9c4f49031da5014fbce0583c027" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "animeTrendConnections" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c86477c5405026fd40ee15a1cd1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "staffConnections" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d62f7f3d7a61206af8b132f064b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "studios" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "idAnilist" integer NOT NULL, "name" character varying NOT NULL, "isAnimationStudio" boolean NOT NULL, "siteUrl" character varying, "favorites" integer, "studioConnectionId" uuid, CONSTRAINT "PK_76ff398ef5041c4b42618ed6111" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_c4bbe658915e6fb4e79bd0ffe3" ON "studios" ("idAnilist") `);
        await queryRunner.query(`CREATE TABLE "studioEdges" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "idAnilist" integer NOT NULL, "isMain" boolean NOT NULL, "favouriteOrder" integer, "nodeId" uuid, "studioConnectionId" uuid, CONSTRAINT "REL_587b61d2d084c8e936af309dee" UNIQUE ("nodeId"), CONSTRAINT "PK_3039477eb6e70f3c777d276dd17" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_072967b0dd67421d3c04f8a1d4" ON "studioEdges" ("idAnilist") `);
        await queryRunner.query(`CREATE TABLE "studioConnections" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8eb062bf53eb0b3a257bfc7ac52" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."animeStreamingEpisodes_translationtype_enum" AS ENUM('DUBBING_TRANSLATION', 'SUBBING_TRANSLATION')`);
        await queryRunner.query(`CREATE TABLE "animeStreamingEpisodes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "translationType" "public"."animeStreamingEpisodes_translationtype_enum", "language" character varying, "site" character varying, "title" character varying, "thumbnail" character varying, "url" character varying, "cachedProxy" character varying, "mediaExternalLinkId" uuid, CONSTRAINT "PK_e88435cc2836e74e8a844940442" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."mediaExternalLinks_type_enum" AS ENUM('INFO', 'STREAMING', 'SOCIAL')`);
        await queryRunner.query(`CREATE TABLE "mediaExternalLinks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "site" character varying, "siteId" integer, "type" "public"."mediaExternalLinks_type_enum", "language" character varying, "color" character varying, "icon" character varying, "notes" character varying, "isDisabled" boolean, "animeId" uuid, CONSTRAINT "PK_1df908b860d285c6e316af30d9b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."anime_format_enum" AS ENUM('TV', 'TV_SHORT', 'MOVIE', 'SPECIAL', 'OVA', 'ONA', 'MUSIC')`);
        await queryRunner.query(`CREATE TYPE "public"."anime_status_enum" AS ENUM('FINISHED', 'RELEASING', 'NOT_YET_RELEASED', 'CANCELLED', 'HIATUS')`);
        await queryRunner.query(`CREATE TYPE "public"."anime_season_enum" AS ENUM('WINTER', 'SPRING', 'SUMMER', 'FALL')`);
        await queryRunner.query(`CREATE TYPE "public"."anime_source_enum" AS ENUM('ORIGINAL', 'MANGA', 'LIGHT_NOVEL', 'VISUAL_NOVEL', 'VIDEO_GAME', 'OTHER', 'NOVEL', 'DOUJINSHI', 'ANIME', 'WEB_NOVEL', 'LIVE_ACTION', 'GAME', 'COMIC', 'MULTIMEDIA_PROJECT', 'PICTURE_BOOK')`);
        await queryRunner.query(`CREATE TABLE "anime" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "idAnilist" integer NOT NULL, "idMal" integer, "format" "public"."anime_format_enum", "status" "public"."anime_status_enum", "season" "public"."anime_season_enum", "seasonYear" integer, "seasonInt" integer, "episodes" integer, "duration" integer, "countryOfOrigin" character varying, "isLicensed" boolean, "source" "public"."anime_source_enum", "hashtag" character varying, "updateAt" integer, "bannerImage" character varying, "averageScore" integer, "meanScore" integer, "popularity" integer, "isAdult" boolean, "startDateId" uuid, "endDateId" uuid, "titleId" uuid, "descriptionId" uuid, "trailerId" uuid, "coverImageId" uuid, "relationsId" uuid, "charactersId" uuid, "staffId" uuid, "studiosId" uuid, "nextAiringEpisodeId" uuid, "airingScheduleId" uuid, "trendsId" uuid, CONSTRAINT "REL_4d99fc327cc9f0fc34a05f6706" UNIQUE ("startDateId"), CONSTRAINT "REL_1a2494e998053d2b0e5eb5ad46" UNIQUE ("endDateId"), CONSTRAINT "REL_d77759d1bc7c55e0b3f1d1449e" UNIQUE ("titleId"), CONSTRAINT "REL_81f89b0f4b6de4760ee283a47c" UNIQUE ("descriptionId"), CONSTRAINT "REL_a688e5ec3932b30ebb3cc119b6" UNIQUE ("trailerId"), CONSTRAINT "REL_1bd9c93d69059b6146b792d4bc" UNIQUE ("coverImageId"), CONSTRAINT "REL_b9f5dc5f29cd336c22ab3d5c6d" UNIQUE ("charactersId"), CONSTRAINT "REL_dfe89612d92ff0ee058841868c" UNIQUE ("staffId"), CONSTRAINT "REL_8dd4932f3d882053f7ada21997" UNIQUE ("studiosId"), CONSTRAINT "REL_0174ae6b07e3bf8b223524d98f" UNIQUE ("nextAiringEpisodeId"), CONSTRAINT "REL_ca5cfc79ac915919808cf8d379" UNIQUE ("airingScheduleId"), CONSTRAINT "REL_6a62cfc0427cfda5f2adaa4154" UNIQUE ("trendsId"), CONSTRAINT "PK_6e567f73ed63fd388a7734cbdd3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_c384e2c3f8bbed21d06b6211ba" ON "anime" ("idAnilist") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_2a46b90863889947842d87cd72" ON "anime" ("idMal") `);
        await queryRunner.query(`CREATE TYPE "public"."characterEdges_role_enum" AS ENUM('MAIN', 'SUPPORTING', 'BACKGROUND')`);
        await queryRunner.query(`CREATE TABLE "characterEdges" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "idAnilist" integer NOT NULL, "role" "public"."characterEdges_role_enum", "name" character varying, "characterConnectionId" uuid, "nodeId" uuid, CONSTRAINT "REL_71ba3ba89ef4efdeb47c2a7d1d" UNIQUE ("nodeId"), CONSTRAINT "PK_85c031d5e0197252eae05266719" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_ac114626ed593ef907b44a4a7a" ON "characterEdges" ("idAnilist") `);
        await queryRunner.query(`CREATE TABLE "characterConnections" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_dea894714af705c8041546fb9b4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "staffNames" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "first" character varying, "middle" character varying, "last" character varying, "full" character varying, "native" character varying, CONSTRAINT "PK_97da859497cc8630fee2359eb86" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "staffAlternative" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying, "staffNameId" uuid, CONSTRAINT "PK_4d2eb7f07b38db7bd68e0761612" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "staffImages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "large" character varying, "medium" character varying, CONSTRAINT "PK_b1a571de0c95409cb5b2b82d839" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "staffYearActives" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "startYear" integer, "endYear" integer, CONSTRAINT "PK_160386f8bf63a3efaef68f8a8e7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "staffs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "idAnilist" integer NOT NULL, "languageV2" character varying, "description" character varying, "gender" character varying, "age" integer, "homeTown" character varying, "bloodType" character varying, "favorites" integer, "staffConnectionId" uuid, "nameId" uuid, "imageId" uuid, "dateOfBirthId" uuid, "dateOfDeathId" uuid, "yearsActiveId" uuid, "charactersId" uuid, CONSTRAINT "REL_dcf023e3eb3e40bf4a4d0779a3" UNIQUE ("nameId"), CONSTRAINT "REL_2a7b7e47eca9c497526c8a193c" UNIQUE ("imageId"), CONSTRAINT "REL_455328978b7877032b5ed63811" UNIQUE ("dateOfBirthId"), CONSTRAINT "REL_cd7e5d95b3a3c02d9419bb7907" UNIQUE ("dateOfDeathId"), CONSTRAINT "REL_3ef5ad3a02d08a8d41597a99e0" UNIQUE ("yearsActiveId"), CONSTRAINT "REL_320e62ed8035328cc1069927b6" UNIQUE ("charactersId"), CONSTRAINT "PK_f3fec5e06209b46afdf8accf117" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_65e4e93fe6e9130da9f3d35c0c" ON "staffs" ("idAnilist") `);
        await queryRunner.query(`CREATE TABLE "staffEdges" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "idAnilist" integer NOT NULL, "role" character varying, "favouriteOrder" integer, "staffConnectionId" uuid, "nodeId" uuid, CONSTRAINT "REL_78531a468e674565af82f1aa71" UNIQUE ("nodeId"), CONSTRAINT "PK_d1ca8cf4a32b7e7fb32855d6c8a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_a7eed90e10f07147a33005ec8a" ON "staffEdges" ("idAnilist") `);
        await queryRunner.query(`CREATE TABLE "reviews" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_231ae565c273ee700b283f15c1d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "aniSpaceLogs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "executeTime" character varying, "requestObject" text, "tracePath" text, "errorMessage" text, "notes" text, CONSTRAINT "PK_5c3e70948132fbe3dc437a4a93b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "anime_edges_characters_characters" ("animeEdgesId" uuid NOT NULL, "charactersId" uuid NOT NULL, CONSTRAINT "PK_874e0f7a352e522aae1e041be2f" PRIMARY KEY ("animeEdgesId", "charactersId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ad83d6b271377bb1595d6f94bf" ON "anime_edges_characters_characters" ("animeEdgesId") `);
        await queryRunner.query(`CREATE INDEX "IDX_2e8ace39c86082725c49124c82" ON "anime_edges_characters_characters" ("charactersId") `);
        await queryRunner.query(`CREATE TABLE "anime_edges_voice_actors_staffs" ("animeEdgesId" uuid NOT NULL, "staffsId" uuid NOT NULL, CONSTRAINT "PK_6b1a15f0d59a3e10ce7267e0801" PRIMARY KEY ("animeEdgesId", "staffsId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a7a06ea3a61bb6a60fe474b27d" ON "anime_edges_voice_actors_staffs" ("animeEdgesId") `);
        await queryRunner.query(`CREATE INDEX "IDX_af9c99e3ba95caa1b56c166bba" ON "anime_edges_voice_actors_staffs" ("staffsId") `);
        await queryRunner.query(`CREATE TABLE "anime_genres_anime_genres" ("animeId" uuid NOT NULL, "animeGenresId" uuid NOT NULL, "animeGenresGenre" character varying NOT NULL, CONSTRAINT "PK_2dd2208bb8ae1ef6975cd493738" PRIMARY KEY ("animeId", "animeGenresId", "animeGenresGenre"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b79c4a41dd8d226b5f3b78d06c" ON "anime_genres_anime_genres" ("animeId") `);
        await queryRunner.query(`CREATE INDEX "IDX_e20cb7b9769fc6138a33b7785e" ON "anime_genres_anime_genres" ("animeGenresId", "animeGenresGenre") `);
        await queryRunner.query(`CREATE TABLE "anime_tags_anime_tags" ("animeId" uuid NOT NULL, "animeTagsId" uuid NOT NULL, CONSTRAINT "PK_236131593e1b10771769a8f20a1" PRIMARY KEY ("animeId", "animeTagsId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f463555e086f5be0db545a802a" ON "anime_tags_anime_tags" ("animeId") `);
        await queryRunner.query(`CREATE INDEX "IDX_d340f634339dee3467e3f54b13" ON "anime_tags_anime_tags" ("animeTagsId") `);
        await queryRunner.query(`CREATE TABLE "character_edges_anime_anime" ("characterEdgesId" uuid NOT NULL, "animeId" uuid NOT NULL, CONSTRAINT "PK_46142a918c7ba6d72ba66ecd844" PRIMARY KEY ("characterEdgesId", "animeId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6c2650d5f3b46a3a80e9df900b" ON "character_edges_anime_anime" ("characterEdgesId") `);
        await queryRunner.query(`CREATE INDEX "IDX_c5da32f0f95e9c4d89f7e7a0db" ON "character_edges_anime_anime" ("animeId") `);
        await queryRunner.query(`ALTER TABLE "characterAlternatives" ADD CONSTRAINT "FK_3ce240a6ec68506f0f4fe1cd0b7" FOREIGN KEY ("characterNameId") REFERENCES "characterNames"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "characterAlternativeSpoilers" ADD CONSTRAINT "FK_522f5eb3eea96bb1e26ea5a353e" FOREIGN KEY ("characterNameId") REFERENCES "characterNames"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "airingScheduleEdges" ADD CONSTRAINT "FK_428b3a1db4a2d7f540e74d287a3" FOREIGN KEY ("nodeId") REFERENCES "airingSchedules"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "airingScheduleEdges" ADD CONSTRAINT "FK_905885a449846bb089a2a153c5f" FOREIGN KEY ("airingScheduleConnectionId") REFERENCES "airingScheduleConnections"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "airingSchedules" ADD CONSTRAINT "FK_1ec3ba088e8c9ab23538239704e" FOREIGN KEY ("animeId") REFERENCES "anime"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "airingSchedules" ADD CONSTRAINT "FK_9a66e87e84d293e4e2cd5f4a61b" FOREIGN KEY ("airingScheduleConnectionId") REFERENCES "airingScheduleConnections"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "animeSynonyms" ADD CONSTRAINT "FK_bf003e635980d29f28f295dfcaa" FOREIGN KEY ("animeId") REFERENCES "anime"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "animeRanks" ADD CONSTRAINT "FK_91d97a50bc6813283efee7a5a04" FOREIGN KEY ("animeId") REFERENCES "anime"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "characters" ADD CONSTRAINT "FK_f43955db99a8d593b618e2d3920" FOREIGN KEY ("nameId") REFERENCES "characterNames"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "characters" ADD CONSTRAINT "FK_431435bea921157c2dfb887faa6" FOREIGN KEY ("characterConnectionId") REFERENCES "characterConnections"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "characters" ADD CONSTRAINT "FK_6d88ae463bc7e775b6679f7adb6" FOREIGN KEY ("imageId") REFERENCES "characterImages"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "characters" ADD CONSTRAINT "FK_158bcaae805ac42d87eaf9f7cf4" FOREIGN KEY ("dateOfBirthId") REFERENCES "fuzzyDates"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "staffRoleTypes" ADD CONSTRAINT "FK_18861189579edd1b26bae89e68c" FOREIGN KEY ("animeEdgeId") REFERENCES "animeEdges"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "staffRoleTypes" ADD CONSTRAINT "FK_f9c4eac13608dd9f2eef4265dd7" FOREIGN KEY ("voiceActorId") REFERENCES "staffs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "animeEdges" ADD CONSTRAINT "FK_f0fd72521ee3cc8951dcb8ab0e5" FOREIGN KEY ("animeConnectionId") REFERENCES "animeConnections"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "animeEdges" ADD CONSTRAINT "FK_63e3b515675c9db42a3533a9a15" FOREIGN KEY ("nodeId") REFERENCES "anime"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "animeTrends" ADD CONSTRAINT "FK_d4e375a27a2792b08744f7ba660" FOREIGN KEY ("animeId") REFERENCES "anime"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "animeTrends" ADD CONSTRAINT "FK_89e5245e98874e83d628b00da47" FOREIGN KEY ("animeTrendConnectionId") REFERENCES "animeTrendConnections"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "animeTrendEdges" ADD CONSTRAINT "FK_be6efd17993fc49a33cbca09c4d" FOREIGN KEY ("nodeId") REFERENCES "animeTrends"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "animeTrendEdges" ADD CONSTRAINT "FK_05eb2b0c85b4e339c4655d4f8da" FOREIGN KEY ("animeTrendConnectionId") REFERENCES "animeTrendConnections"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "studios" ADD CONSTRAINT "FK_bdfe2ec2a3a1b7cc35428cd351c" FOREIGN KEY ("studioConnectionId") REFERENCES "studioConnections"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "studioEdges" ADD CONSTRAINT "FK_587b61d2d084c8e936af309dee7" FOREIGN KEY ("nodeId") REFERENCES "studios"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "studioEdges" ADD CONSTRAINT "FK_6cf290b13f400b8f5de3d18dfe6" FOREIGN KEY ("studioConnectionId") REFERENCES "studioConnections"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "animeStreamingEpisodes" ADD CONSTRAINT "FK_72fbea5bdbb71f41aaea1cc4394" FOREIGN KEY ("mediaExternalLinkId") REFERENCES "mediaExternalLinks"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mediaExternalLinks" ADD CONSTRAINT "FK_a18152c504a47c79fb122ca118e" FOREIGN KEY ("animeId") REFERENCES "anime"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "anime" ADD CONSTRAINT "FK_4d99fc327cc9f0fc34a05f6706a" FOREIGN KEY ("startDateId") REFERENCES "fuzzyDates"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "anime" ADD CONSTRAINT "FK_1a2494e998053d2b0e5eb5ad468" FOREIGN KEY ("endDateId") REFERENCES "fuzzyDates"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "anime" ADD CONSTRAINT "FK_d77759d1bc7c55e0b3f1d1449e1" FOREIGN KEY ("titleId") REFERENCES "animeTitles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "anime" ADD CONSTRAINT "FK_81f89b0f4b6de4760ee283a47cd" FOREIGN KEY ("descriptionId") REFERENCES "animeDescriptions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "anime" ADD CONSTRAINT "FK_a688e5ec3932b30ebb3cc119b6f" FOREIGN KEY ("trailerId") REFERENCES "animeTrailers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "anime" ADD CONSTRAINT "FK_1bd9c93d69059b6146b792d4bc0" FOREIGN KEY ("coverImageId") REFERENCES "animeCoverImages"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "anime" ADD CONSTRAINT "FK_df566d2fec6e79294fec3648b6c" FOREIGN KEY ("relationsId") REFERENCES "animeConnections"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "anime" ADD CONSTRAINT "FK_b9f5dc5f29cd336c22ab3d5c6d3" FOREIGN KEY ("charactersId") REFERENCES "characterConnections"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "anime" ADD CONSTRAINT "FK_dfe89612d92ff0ee058841868c5" FOREIGN KEY ("staffId") REFERENCES "staffConnections"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "anime" ADD CONSTRAINT "FK_8dd4932f3d882053f7ada219975" FOREIGN KEY ("studiosId") REFERENCES "studioConnections"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "anime" ADD CONSTRAINT "FK_0174ae6b07e3bf8b223524d98f3" FOREIGN KEY ("nextAiringEpisodeId") REFERENCES "airingSchedules"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "anime" ADD CONSTRAINT "FK_ca5cfc79ac915919808cf8d3791" FOREIGN KEY ("airingScheduleId") REFERENCES "airingScheduleConnections"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "anime" ADD CONSTRAINT "FK_6a62cfc0427cfda5f2adaa41546" FOREIGN KEY ("trendsId") REFERENCES "animeTrendConnections"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "characterEdges" ADD CONSTRAINT "FK_6e1113912801bbcb0e4e22b80e0" FOREIGN KEY ("characterConnectionId") REFERENCES "characterConnections"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "characterEdges" ADD CONSTRAINT "FK_71ba3ba89ef4efdeb47c2a7d1db" FOREIGN KEY ("nodeId") REFERENCES "characters"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "staffAlternative" ADD CONSTRAINT "FK_49aa138f3754a23bee7164934ac" FOREIGN KEY ("staffNameId") REFERENCES "staffNames"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "staffs" ADD CONSTRAINT "FK_1174f1795cb7d96e2c1babb57f0" FOREIGN KEY ("staffConnectionId") REFERENCES "staffConnections"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "staffs" ADD CONSTRAINT "FK_dcf023e3eb3e40bf4a4d0779a3f" FOREIGN KEY ("nameId") REFERENCES "staffNames"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "staffs" ADD CONSTRAINT "FK_2a7b7e47eca9c497526c8a193cc" FOREIGN KEY ("imageId") REFERENCES "staffImages"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "staffs" ADD CONSTRAINT "FK_455328978b7877032b5ed638114" FOREIGN KEY ("dateOfBirthId") REFERENCES "fuzzyDates"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "staffs" ADD CONSTRAINT "FK_cd7e5d95b3a3c02d9419bb79077" FOREIGN KEY ("dateOfDeathId") REFERENCES "fuzzyDates"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "staffs" ADD CONSTRAINT "FK_3ef5ad3a02d08a8d41597a99e0e" FOREIGN KEY ("yearsActiveId") REFERENCES "staffYearActives"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "staffs" ADD CONSTRAINT "FK_320e62ed8035328cc1069927b6a" FOREIGN KEY ("charactersId") REFERENCES "characterConnections"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "staffEdges" ADD CONSTRAINT "FK_af3e8ca480078794b43e75ee11a" FOREIGN KEY ("staffConnectionId") REFERENCES "staffConnections"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "staffEdges" ADD CONSTRAINT "FK_78531a468e674565af82f1aa715" FOREIGN KEY ("nodeId") REFERENCES "staffs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "anime_edges_characters_characters" ADD CONSTRAINT "FK_ad83d6b271377bb1595d6f94bf0" FOREIGN KEY ("animeEdgesId") REFERENCES "animeEdges"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "anime_edges_characters_characters" ADD CONSTRAINT "FK_2e8ace39c86082725c49124c82a" FOREIGN KEY ("charactersId") REFERENCES "characters"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "anime_edges_voice_actors_staffs" ADD CONSTRAINT "FK_a7a06ea3a61bb6a60fe474b27d1" FOREIGN KEY ("animeEdgesId") REFERENCES "animeEdges"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "anime_edges_voice_actors_staffs" ADD CONSTRAINT "FK_af9c99e3ba95caa1b56c166bbad" FOREIGN KEY ("staffsId") REFERENCES "staffs"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "anime_genres_anime_genres" ADD CONSTRAINT "FK_b79c4a41dd8d226b5f3b78d06cb" FOREIGN KEY ("animeId") REFERENCES "anime"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "anime_genres_anime_genres" ADD CONSTRAINT "FK_e20cb7b9769fc6138a33b7785eb" FOREIGN KEY ("animeGenresId", "animeGenresGenre") REFERENCES "animeGenres"("id","genre") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "anime_tags_anime_tags" ADD CONSTRAINT "FK_f463555e086f5be0db545a802a8" FOREIGN KEY ("animeId") REFERENCES "anime"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "anime_tags_anime_tags" ADD CONSTRAINT "FK_d340f634339dee3467e3f54b138" FOREIGN KEY ("animeTagsId") REFERENCES "animeTags"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "character_edges_anime_anime" ADD CONSTRAINT "FK_6c2650d5f3b46a3a80e9df900b6" FOREIGN KEY ("characterEdgesId") REFERENCES "characterEdges"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "character_edges_anime_anime" ADD CONSTRAINT "FK_c5da32f0f95e9c4d89f7e7a0db4" FOREIGN KEY ("animeId") REFERENCES "anime"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "character_edges_anime_anime" DROP CONSTRAINT "FK_c5da32f0f95e9c4d89f7e7a0db4"`);
        await queryRunner.query(`ALTER TABLE "character_edges_anime_anime" DROP CONSTRAINT "FK_6c2650d5f3b46a3a80e9df900b6"`);
        await queryRunner.query(`ALTER TABLE "anime_tags_anime_tags" DROP CONSTRAINT "FK_d340f634339dee3467e3f54b138"`);
        await queryRunner.query(`ALTER TABLE "anime_tags_anime_tags" DROP CONSTRAINT "FK_f463555e086f5be0db545a802a8"`);
        await queryRunner.query(`ALTER TABLE "anime_genres_anime_genres" DROP CONSTRAINT "FK_e20cb7b9769fc6138a33b7785eb"`);
        await queryRunner.query(`ALTER TABLE "anime_genres_anime_genres" DROP CONSTRAINT "FK_b79c4a41dd8d226b5f3b78d06cb"`);
        await queryRunner.query(`ALTER TABLE "anime_edges_voice_actors_staffs" DROP CONSTRAINT "FK_af9c99e3ba95caa1b56c166bbad"`);
        await queryRunner.query(`ALTER TABLE "anime_edges_voice_actors_staffs" DROP CONSTRAINT "FK_a7a06ea3a61bb6a60fe474b27d1"`);
        await queryRunner.query(`ALTER TABLE "anime_edges_characters_characters" DROP CONSTRAINT "FK_2e8ace39c86082725c49124c82a"`);
        await queryRunner.query(`ALTER TABLE "anime_edges_characters_characters" DROP CONSTRAINT "FK_ad83d6b271377bb1595d6f94bf0"`);
        await queryRunner.query(`ALTER TABLE "staffEdges" DROP CONSTRAINT "FK_78531a468e674565af82f1aa715"`);
        await queryRunner.query(`ALTER TABLE "staffEdges" DROP CONSTRAINT "FK_af3e8ca480078794b43e75ee11a"`);
        await queryRunner.query(`ALTER TABLE "staffs" DROP CONSTRAINT "FK_320e62ed8035328cc1069927b6a"`);
        await queryRunner.query(`ALTER TABLE "staffs" DROP CONSTRAINT "FK_3ef5ad3a02d08a8d41597a99e0e"`);
        await queryRunner.query(`ALTER TABLE "staffs" DROP CONSTRAINT "FK_cd7e5d95b3a3c02d9419bb79077"`);
        await queryRunner.query(`ALTER TABLE "staffs" DROP CONSTRAINT "FK_455328978b7877032b5ed638114"`);
        await queryRunner.query(`ALTER TABLE "staffs" DROP CONSTRAINT "FK_2a7b7e47eca9c497526c8a193cc"`);
        await queryRunner.query(`ALTER TABLE "staffs" DROP CONSTRAINT "FK_dcf023e3eb3e40bf4a4d0779a3f"`);
        await queryRunner.query(`ALTER TABLE "staffs" DROP CONSTRAINT "FK_1174f1795cb7d96e2c1babb57f0"`);
        await queryRunner.query(`ALTER TABLE "staffAlternative" DROP CONSTRAINT "FK_49aa138f3754a23bee7164934ac"`);
        await queryRunner.query(`ALTER TABLE "characterEdges" DROP CONSTRAINT "FK_71ba3ba89ef4efdeb47c2a7d1db"`);
        await queryRunner.query(`ALTER TABLE "characterEdges" DROP CONSTRAINT "FK_6e1113912801bbcb0e4e22b80e0"`);
        await queryRunner.query(`ALTER TABLE "anime" DROP CONSTRAINT "FK_6a62cfc0427cfda5f2adaa41546"`);
        await queryRunner.query(`ALTER TABLE "anime" DROP CONSTRAINT "FK_ca5cfc79ac915919808cf8d3791"`);
        await queryRunner.query(`ALTER TABLE "anime" DROP CONSTRAINT "FK_0174ae6b07e3bf8b223524d98f3"`);
        await queryRunner.query(`ALTER TABLE "anime" DROP CONSTRAINT "FK_8dd4932f3d882053f7ada219975"`);
        await queryRunner.query(`ALTER TABLE "anime" DROP CONSTRAINT "FK_dfe89612d92ff0ee058841868c5"`);
        await queryRunner.query(`ALTER TABLE "anime" DROP CONSTRAINT "FK_b9f5dc5f29cd336c22ab3d5c6d3"`);
        await queryRunner.query(`ALTER TABLE "anime" DROP CONSTRAINT "FK_df566d2fec6e79294fec3648b6c"`);
        await queryRunner.query(`ALTER TABLE "anime" DROP CONSTRAINT "FK_1bd9c93d69059b6146b792d4bc0"`);
        await queryRunner.query(`ALTER TABLE "anime" DROP CONSTRAINT "FK_a688e5ec3932b30ebb3cc119b6f"`);
        await queryRunner.query(`ALTER TABLE "anime" DROP CONSTRAINT "FK_81f89b0f4b6de4760ee283a47cd"`);
        await queryRunner.query(`ALTER TABLE "anime" DROP CONSTRAINT "FK_d77759d1bc7c55e0b3f1d1449e1"`);
        await queryRunner.query(`ALTER TABLE "anime" DROP CONSTRAINT "FK_1a2494e998053d2b0e5eb5ad468"`);
        await queryRunner.query(`ALTER TABLE "anime" DROP CONSTRAINT "FK_4d99fc327cc9f0fc34a05f6706a"`);
        await queryRunner.query(`ALTER TABLE "mediaExternalLinks" DROP CONSTRAINT "FK_a18152c504a47c79fb122ca118e"`);
        await queryRunner.query(`ALTER TABLE "animeStreamingEpisodes" DROP CONSTRAINT "FK_72fbea5bdbb71f41aaea1cc4394"`);
        await queryRunner.query(`ALTER TABLE "studioEdges" DROP CONSTRAINT "FK_6cf290b13f400b8f5de3d18dfe6"`);
        await queryRunner.query(`ALTER TABLE "studioEdges" DROP CONSTRAINT "FK_587b61d2d084c8e936af309dee7"`);
        await queryRunner.query(`ALTER TABLE "studios" DROP CONSTRAINT "FK_bdfe2ec2a3a1b7cc35428cd351c"`);
        await queryRunner.query(`ALTER TABLE "animeTrendEdges" DROP CONSTRAINT "FK_05eb2b0c85b4e339c4655d4f8da"`);
        await queryRunner.query(`ALTER TABLE "animeTrendEdges" DROP CONSTRAINT "FK_be6efd17993fc49a33cbca09c4d"`);
        await queryRunner.query(`ALTER TABLE "animeTrends" DROP CONSTRAINT "FK_89e5245e98874e83d628b00da47"`);
        await queryRunner.query(`ALTER TABLE "animeTrends" DROP CONSTRAINT "FK_d4e375a27a2792b08744f7ba660"`);
        await queryRunner.query(`ALTER TABLE "animeEdges" DROP CONSTRAINT "FK_63e3b515675c9db42a3533a9a15"`);
        await queryRunner.query(`ALTER TABLE "animeEdges" DROP CONSTRAINT "FK_f0fd72521ee3cc8951dcb8ab0e5"`);
        await queryRunner.query(`ALTER TABLE "staffRoleTypes" DROP CONSTRAINT "FK_f9c4eac13608dd9f2eef4265dd7"`);
        await queryRunner.query(`ALTER TABLE "staffRoleTypes" DROP CONSTRAINT "FK_18861189579edd1b26bae89e68c"`);
        await queryRunner.query(`ALTER TABLE "characters" DROP CONSTRAINT "FK_158bcaae805ac42d87eaf9f7cf4"`);
        await queryRunner.query(`ALTER TABLE "characters" DROP CONSTRAINT "FK_6d88ae463bc7e775b6679f7adb6"`);
        await queryRunner.query(`ALTER TABLE "characters" DROP CONSTRAINT "FK_431435bea921157c2dfb887faa6"`);
        await queryRunner.query(`ALTER TABLE "characters" DROP CONSTRAINT "FK_f43955db99a8d593b618e2d3920"`);
        await queryRunner.query(`ALTER TABLE "animeRanks" DROP CONSTRAINT "FK_91d97a50bc6813283efee7a5a04"`);
        await queryRunner.query(`ALTER TABLE "animeSynonyms" DROP CONSTRAINT "FK_bf003e635980d29f28f295dfcaa"`);
        await queryRunner.query(`ALTER TABLE "airingSchedules" DROP CONSTRAINT "FK_9a66e87e84d293e4e2cd5f4a61b"`);
        await queryRunner.query(`ALTER TABLE "airingSchedules" DROP CONSTRAINT "FK_1ec3ba088e8c9ab23538239704e"`);
        await queryRunner.query(`ALTER TABLE "airingScheduleEdges" DROP CONSTRAINT "FK_905885a449846bb089a2a153c5f"`);
        await queryRunner.query(`ALTER TABLE "airingScheduleEdges" DROP CONSTRAINT "FK_428b3a1db4a2d7f540e74d287a3"`);
        await queryRunner.query(`ALTER TABLE "characterAlternativeSpoilers" DROP CONSTRAINT "FK_522f5eb3eea96bb1e26ea5a353e"`);
        await queryRunner.query(`ALTER TABLE "characterAlternatives" DROP CONSTRAINT "FK_3ce240a6ec68506f0f4fe1cd0b7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c5da32f0f95e9c4d89f7e7a0db"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6c2650d5f3b46a3a80e9df900b"`);
        await queryRunner.query(`DROP TABLE "character_edges_anime_anime"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d340f634339dee3467e3f54b13"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f463555e086f5be0db545a802a"`);
        await queryRunner.query(`DROP TABLE "anime_tags_anime_tags"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e20cb7b9769fc6138a33b7785e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b79c4a41dd8d226b5f3b78d06c"`);
        await queryRunner.query(`DROP TABLE "anime_genres_anime_genres"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_af9c99e3ba95caa1b56c166bba"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a7a06ea3a61bb6a60fe474b27d"`);
        await queryRunner.query(`DROP TABLE "anime_edges_voice_actors_staffs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2e8ace39c86082725c49124c82"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ad83d6b271377bb1595d6f94bf"`);
        await queryRunner.query(`DROP TABLE "anime_edges_characters_characters"`);
        await queryRunner.query(`DROP TABLE "aniSpaceLogs"`);
        await queryRunner.query(`DROP TABLE "reviews"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a7eed90e10f07147a33005ec8a"`);
        await queryRunner.query(`DROP TABLE "staffEdges"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_65e4e93fe6e9130da9f3d35c0c"`);
        await queryRunner.query(`DROP TABLE "staffs"`);
        await queryRunner.query(`DROP TABLE "staffYearActives"`);
        await queryRunner.query(`DROP TABLE "staffImages"`);
        await queryRunner.query(`DROP TABLE "staffAlternative"`);
        await queryRunner.query(`DROP TABLE "staffNames"`);
        await queryRunner.query(`DROP TABLE "characterConnections"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ac114626ed593ef907b44a4a7a"`);
        await queryRunner.query(`DROP TABLE "characterEdges"`);
        await queryRunner.query(`DROP TYPE "public"."characterEdges_role_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2a46b90863889947842d87cd72"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c384e2c3f8bbed21d06b6211ba"`);
        await queryRunner.query(`DROP TABLE "anime"`);
        await queryRunner.query(`DROP TYPE "public"."anime_source_enum"`);
        await queryRunner.query(`DROP TYPE "public"."anime_season_enum"`);
        await queryRunner.query(`DROP TYPE "public"."anime_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."anime_format_enum"`);
        await queryRunner.query(`DROP TABLE "mediaExternalLinks"`);
        await queryRunner.query(`DROP TYPE "public"."mediaExternalLinks_type_enum"`);
        await queryRunner.query(`DROP TABLE "animeStreamingEpisodes"`);
        await queryRunner.query(`DROP TYPE "public"."animeStreamingEpisodes_translationtype_enum"`);
        await queryRunner.query(`DROP TABLE "studioConnections"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_072967b0dd67421d3c04f8a1d4"`);
        await queryRunner.query(`DROP TABLE "studioEdges"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c4bbe658915e6fb4e79bd0ffe3"`);
        await queryRunner.query(`DROP TABLE "studios"`);
        await queryRunner.query(`DROP TABLE "staffConnections"`);
        await queryRunner.query(`DROP TABLE "animeTrendConnections"`);
        await queryRunner.query(`DROP TABLE "animeTrendEdges"`);
        await queryRunner.query(`DROP TABLE "animeTrends"`);
        await queryRunner.query(`DROP TABLE "animeConnections"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ad4ef85b2cacf6c42f6a5769c8"`);
        await queryRunner.query(`DROP TABLE "animeEdges"`);
        await queryRunner.query(`DROP TYPE "public"."animeEdges_characterrole_enum"`);
        await queryRunner.query(`DROP TYPE "public"."animeEdges_relationtype_enum"`);
        await queryRunner.query(`DROP TABLE "staffRoleTypes"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8b2fe437e585f2a356df6e863b"`);
        await queryRunner.query(`DROP TABLE "characters"`);
        await queryRunner.query(`DROP TABLE "fuzzyDates"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bd2b05ba1470f6df4dcf05b5d2"`);
        await queryRunner.query(`DROP TABLE "animeRanks"`);
        await queryRunner.query(`DROP TYPE "public"."animeRanks_season_enum"`);
        await queryRunner.query(`DROP TYPE "public"."animeRanks_format_enum"`);
        await queryRunner.query(`DROP TYPE "public"."animeRanks_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c983c0d7a7d44ce4a57858e2bd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8c8af58bbb2debc62de8157bc9"`);
        await queryRunner.query(`DROP TABLE "animeTags"`);
        await queryRunner.query(`DROP TABLE "animeSynonyms"`);
        await queryRunner.query(`DROP TABLE "animeGenres"`);
        await queryRunner.query(`DROP TABLE "animeCoverImages"`);
        await queryRunner.query(`DROP TABLE "animeTrailers"`);
        await queryRunner.query(`DROP TABLE "animeDescriptions"`);
        await queryRunner.query(`DROP TABLE "animeTitles"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f6fc472834012ed0d5bf7bf52e"`);
        await queryRunner.query(`DROP TABLE "airingSchedules"`);
        await queryRunner.query(`DROP TABLE "airingScheduleConnections"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e64f63b15a5c37eae8138adce9"`);
        await queryRunner.query(`DROP TABLE "airingScheduleEdges"`);
        await queryRunner.query(`DROP TABLE "characterImages"`);
        await queryRunner.query(`DROP TABLE "characterNames"`);
        await queryRunner.query(`DROP TABLE "characterAlternativeSpoilers"`);
        await queryRunner.query(`DROP TABLE "characterAlternatives"`);
    }

}
