import { registerEnumType } from '@nestjs/graphql';

export enum SynchronizedAnimeEnum {
  ANIME_SCALAR_TYPE = 'ANIME_SCALAR_TYPE',

  SAVE_ANIME_CHARACTERS_TYPE = 'SAVE_ANIME_CHARACTERS_TYPE',
  SAVE_ANIME_RELATIONS_TYPE = 'SAVE_ANIME_RELATIONS_TYPE',
  SAVE_ANIME_STAFF_TYPE = 'SAVE_ANIME_STAFF_TYPE',
  SAVE_ANIME_STUDIO_TYPE = 'SAVE_ANIME_STUDIO_TYPE',

  SAVE_CHARACTERS_TYPE = 'SAVE_CHARACTERS_TYPE',
  SAVE_CHARACTER_ANIME_TYPE = 'SAVE_CHARACTER_ANIME_TYPE',

  SAVE_STAFFS_TYPE = 'SAVE_STAFFS_TYPE',
  SAVE_STAFF_ANIME_TYPE = 'SAVE_STAFF_ANIME_TYPE',
  SAVE_STAFF_CHARACTER_TYPE = 'SAVE_STAFF_CHARACTER_TYPE',

  SAVE_STUDIO_TYPE = 'SAVE_STUDIO_TYPE',
  SAVE_STUDIO_ANIME_TYPE = 'SAVE_STUDIO_ANIME_TYPE'
}

registerEnumType(SynchronizedAnimeEnum, {
  name: 'SynchronizedAnimeEnum',
});
