import { registerEnumType } from '@nestjs/graphql';

export enum SynchronizedAnimeEnum {
  SEARCH_ANIMEVSUB = 'SEARCH_ANIMEVSUB',
  SYNC_ANIMEVSUB = 'SYNC_ANIMEVSUB',
  SYNC_ANIMEVSUB_STREAMING_EPISODES = 'SYNC_ANIMEVSUB_STREAMING_EPISODES',
  SEARCH_ANIMEHAY = 'SEARCH_ANIMEHAY',
  SYNC_ANIMEHAY = 'SYNC_ANIMEHAY',
  SYNC_ANIMEHAY_STREAMING_EPISODES = 'SYNC_ANIMEHAY_STREAMING_EPISODES',
  ANIME_SCALAR_TYPE = 'ANIME_SCALAR_TYPE',

  SAVE_ANIME_CHARACTERS_TYPE = 'SAVE_ANIME_CHARACTERS_TYPE',
  SAVE_ANIME_RELATIONS_TYPE = 'SAVE_ANIME_RELATIONS_TYPE',
  SAVE_ANIME_STAFF_TYPE = 'SAVE_ANIME_STAFF_TYPE',
  SAVE_ANIME_STUDIO_TYPE = 'SAVE_ANIME_STUDIO_TYPE',

  SAVE_CHARACTERS_TYPE = 'SAVE_CHARACTERS_TYPE',
  SAVE_CHARACTER_ANIME_TYPE = 'SAVE_CHARACTER_ANIME_TYPE',

  SAVE_STAFFS_TYPE = 'SAVE_STAFFS_TYPE',
  SAVE_STAFF_ANIME_TYPE = 'SAVE_STAFF_ANIME_TYPE',
  SAVE_STAFF_CHARACTER_TYPE = 'SAVE_STAFF_CHARACTER_TYPE',

  SAVE_STUDIO_TYPE = 'SAVE_STUDIO_TYPE',
  SAVE_STUDIO_ANIME_TYPE = 'SAVE_STUDIO_ANIME_TYPE',
}

registerEnumType(SynchronizedAnimeEnum, {
  name: 'SynchronizedAnimeEnum',
});
